const filmes = [
  {
    id: "ultimato",
    nome: "Vingadores: Ultimato",
    genero: "Ação",
    faixaEtaria: "12 anos",
    ano: 2019,
    tipo: "Filme",
    notaCritica: 4.7,
    sinopse: "Os heróis remanescentes se unem em uma última tentativa de reverter os efeitos causados por Thanos.",
    premio: "Indicado ao Oscar de Melhores Efeitos Visuais (2020)",
    imagem: "https://image.tmdb.org/t/p/w500/9fRX8UKlIW7Lb9GqNsJVakWWFCi.jpg"
  },
  {
    id: "divertidamente2",
    nome: "Divertida Mente 2",
    genero: "Animação",
    faixaEtaria: "Livre",
    ano: 2024,
    tipo: "Filme",
    notaCritica: 4.6,
    sinopse: "Riley entra na adolescência e novas emoções, como Ansiedade, chegam para bagunçar sua central de controle.",
    premio: "Indicado ao Globo de Ouro de Melhor Animação (2025)",
    imagem: "https://image.tmdb.org/t/p/w500/62SAZfLfzhxJWUFJvfIPMw6QUpE.jpg"
  },
  {
    id: "oppenheimer",
    nome: "Oppenheimer",
    genero: "Drama",
    faixaEtaria: "16 anos",
    ano: 2023,
    tipo: "Filme",
    notaCritica: 4.9,
    sinopse: "A história do físico J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
    premio: "Vencedor do Oscar de Melhor Filme (2024)",
    imagem: "https://image.tmdb.org/t/p/w500/1OsQJEoSXBjduuCvDOlRhoEUaHu.jpg"
  },
  {
    id: "round6",
    nome: "Round 6",
    genero: "Suspense",
    faixaEtaria: "18 anos",
    ano: 2021,
    tipo: "Série",
    notaCritica: 4.5,
    sinopse: "Centenas de pessoas endividadas competem em jogos infantis mortais por um grande prêmio em dinheiro.",
    premio: "Vencedora de 6 prêmios Emmy (2022)",
    imagem: "https://image.tmdb.org/t/p/w500/6gcHdboppvplmBWxvROc96NJnmm.jpg"
  },
  {
    id: "thecrown",
    nome: "The Crown",
    genero: "Drama",
    faixaEtaria: "14 anos",
    ano: 2016,
    tipo: "Série",
    notaCritica: 4.4,
    sinopse: "Acompanha o reinado da rainha Elizabeth II e os bastidores da família real britânica.",
    premio: "Vencedora do Globo de Ouro de Melhor Série de Drama (2021)",
    imagem: "https://image.tmdb.org/t/p/w500/ehUMAA3qDR5HNor9DB60g72KNQZ.jpg"
  },
  {
    id: "toystory4",
    nome: "Toy Story 4",
    genero: "Animação",
    faixaEtaria: "Livre",
    ano: 2019,
    tipo: "Filme",
    notaCritica: 4.3,
    sinopse: "Woody e a turma de brinquedos embarcam em uma viagem de estrada e conhecem a independente Gabby Gabby.",
    premio: "Vencedor do Oscar de Melhor Animação (2020)",
    imagem: "https://image.tmdb.org/t/p/w500/csiyO6q8rR74pfgJDjwINzhoick.jpg"
  },
  {
    id: "esposamentirinha",
    nome: "Esposa de Mentirinha",
    genero: "Comédia",
    faixaEtaria: "14 anos",
    ano: 2009,
    tipo: "Filme",
    notaCritica: 4.1,
    sinopse: "Uma executiva prestes a ser deportada convence o assistente a fingir um noivado com ela para evitar a extradição.",
    premio: "Indicada ao People's Choice Awards de Comédia Favorita (2010)",
    imagem: "https://image.tmdb.org/t/p/w500/glC4pDnSieQ9NGU501rfVIqUCTB.jpg"
  },
  {
    id: "bigbangtheory",
    nome: "The Big Bang Theory",
    genero: "Comédia",
    faixaEtaria: "12 anos",
    ano: 2007,
    tipo: "Série",
    notaCritica: 4.5,
    sinopse: "Um grupo de cientistas brilhantes, mas socialmente desajeitados, enfrenta o dia a dia e as dificuldades de se relacionar fora do laboratório.",
    premio: "Jim Parsons venceu 4 vezes o Emmy de Melhor Ator em Comédia",
    imagem: "https://image.tmdb.org/t/p/w500/1oODZKc1dpQZvtZPaZVWR11dzEI.jpg"
  },
  {
    id: "dracula",
    nome: "Drácula de Bram Stoker",
    genero: "Terror",
    faixaEtaria: "16 anos",
    ano: 1992,
    tipo: "Filme",
    notaCritica: 4.2,
    sinopse: "O conde Drácula viaja à Inglaterra em busca de uma jovem que se parece com seu grande amor perdido séculos atrás.",
    premio: "Vencedor de 3 Oscars técnicos (1993)",
    imagem: "https://image.tmdb.org/t/p/w500/ecuP4ZaIHawKmmIaXD5mS55UlhL.jpg"
  },
  {
    id: "armageddon",
    nome: "Armageddon",
    genero: "Ficção Científica",
    faixaEtaria: "12 anos",
    ano: 1998,
    tipo: "Filme",
    notaCritica: 3.9,
    sinopse: "Uma equipe de perfuradores de petróleo é treinada às pressas pela NASA para destruir um asteroide gigante em rota de colisão com a Terra.",
    premio: "Indicado a 4 Oscars técnicos (1999)",
    imagem: "https://image.tmdb.org/t/p/w500/uSS6G9K14Qe6Ywh4IMkgjQBM3a3.jpg"
  },
  {
    id: "titanic",
    nome: "Titanic",
    genero: "Romance",
    faixaEtaria: "12 anos",
    ano: 1997,
    tipo: "Filme",
    notaCritica: 4.8,
    sinopse: "Um artista pobre e uma jovem da alta sociedade vivem um romance proibido a bordo do transatlântico em sua fatídica viagem inaugural.",
    premio: "Vencedor de 11 Oscars, incluindo Melhor Filme (1998)",
    imagem: "https://image.tmdb.org/t/p/w500/As0zX43h3w6kD2NS4uVHu9HKdEh.jpg"
  },
  {
    id: "michaeljacksonthisit",
    nome: "Michael Jackson's This Is It",
    genero: "Documentário",
    faixaEtaria: "Livre",
    ano: 2009,
    tipo: "Filme",
    notaCritica: 4.4,
    sinopse: "Registra os bastidores dos ensaios de Michael Jackson para a turnê que marcaria seu retorno aos palcos.",
    premio: "Um dos documentários musicais de maior bilheteria da história",
    imagem: "https://image.tmdb.org/t/p/w500/gXh43JopeO8BlA661BvlkR6yeqs.jpg"
  },
  {
    id: "magicodeoz",
    nome: "O Mágico de Oz",
    genero: "Musical",
    faixaEtaria: "Livre",
    ano: 1939,
    tipo: "Filme",
    notaCritica: 4.6,
    sinopse: "Dorothy é levada por um tornado à mágica terra de Oz e embarca em uma jornada para encontrar o caminho de volta para casa.",
    premio: "Vencedor do Oscar de Melhor Canção Original, \"Over the Rainbow\" (1940)",
    imagem: "https://image.tmdb.org/t/p/w500/skT3EcFUSWSCpe7XUKTQR8ZTp57.jpg"
  }
];